### ISSUE TITLE
Multiple files upload to a single datasource

### ISSUE THREAD

**Issue by jakubklimek** [payola/LDVMi#42]
Allow upload of multiple ttl (and other?) files to a single datasource.

Use case: Upload data, schema, links - as in Use Case 2.

**Comment by jirihelmich** [comment]
Fixed in https://github.com/payola/LDVMi/commit/0bc7ce81248b49887675247e1b226666bb10e39d .

**Comment by jirihelmich** [comment]
I tested it only with small files, it would be great if you could try to upload some larger samples. Files/TTL contents are pushed to Virtuoso in parallel.

**Comment by jakubklimek** [comment]
Yep, does not work with:
http://opendata.cz/ldvm/ovm-vocab.ttl
https://raw.githubusercontent.com/payola/ldvm/master/rdf/examples/ovm-obce-links.ttl
http://opendata.cz/ldvm/ovm.ttl
and Combine

**Comment by jirihelmich** [comment]
Fixed & tested.

**Comment by jirihelmich** [comment]
http://live.payola.cz:29090/pipelines#/detail/33
