### ISSUE TITLE
Dimension labels in data cube visualization not snown

### ISSUE THREAD

**Issue by martinnec** [payola/LDVMi#46]
See

http://live.payola.cz:29080/visualize/datacube#/id/32?view=chart&chartType=column&isPolar=false&p=bf042521c0e926657d5eb70aa7518b2d

Labels of dimensions are not displayed. For example, this dimension:

http://linked.opendata.cz/ontology/application/mfcrapp/rozpocty/refPeriod

has a label defined (rdfs:label), see

http://internal.opendata.cz:8890/describe/?url=http://linked.opendata.cz/ontology/application/mfcrapp/rozpocty/refPeriod

**Comment by jirihelmich** [comment]
Right now, the app relies on components having a URI. Those are blank nodes, so it's URI is null and that's where it fails.

I need to have a look why is that so and what could be done to avoid this.

**Comment by jirihelmich** [comment]
OK, those labels are somehow ignored, it's looking for them just directly on a a component. URI does not matter.

Was it this datasource?

http://live.payola.cz:29080/components#/detail/datasource/45

**Comment by jirihelmich** [comment]
OK, not somehow, it's just not selected by the query.

```
     <@structureUri> a qb:DataStructureDefinition ;
        qb:component ?c .
     ?c qb:@dimensionType ?dim ;
        rdfs:label ?l ;
        skos:notion ?sn ;
        skos:prefLabel ?spl ;
        qb:order ?order ;
        qb:concept ?concept .                      
```

So ask for labels of ?c, not ?dim. I can change it, I could even support both somehow, but I'm afraid it would be too many optionals for Virtuoso.

Any suggestions?

**Comment by jirihelmich** [comment]
Fixed, was caused by labels not having explicit language, broken by yesterday's modifications. Sorry for the confusion.
