### ISSUE TITLE
Showing labels of dimensions fixed to a single value in the data cube visualization

### ISSUE THREAD

**Issue by martinnec** [payola/LDVMi#47]
For example, here

http://live.payola.cz:29080/visualize/datacube#/id/32?view=chart&chartType=column&isPolar=false&p=bf042521c0e926657d5eb70aa7518b2d

it is hard to understand what is displayed. The problem is that the chosen measure and dimensions fixed to a single values are not shown somehow in the visualization. 

I propose to show (e.g. under the visualized graph) the measures and dimensions which are not visible  in the following form:

- show the title of the data cube (rdfs:label, dcterms:title) as the main title (currently there is fixed "DataCube"
- show the names of chosen measures under the main title as secondary titles
- show pairs [Dimension name] : [Chosen value] at the bottom of the graph for each dimension which is not visualized in the graph

See example:

![image](https://cloud.githubusercontent.com/assets/4235208/7469040/789358da-f30f-11e4-9a89-79598a6cd3a4.png)

**Comment by jirihelmich** [comment]
deploying first 2 tasks

**Comment by jirihelmich** [comment]
- one measure mode

https://www.dropbox.com/s/ydvc3hj43yadvns/Screenshot%202015-05-06%2013.28.37.png?dl=0

Note that measure name is at Y axis, I think it's more appropriate than having it as a subtitle.Single measure mode:

- title: DSD label (will be changed to dataset title when datasets supported)
- subtitle: null
- yAxis: measure label
- xAxis: last multi-valued dimension label
- legend: list of labels of single-valued dimensions and label of that single value

![screenshot 2015-05-06 13 28 37](https://cloud.githubusercontent.com/assets/174768/7492770/b6c0ccd6-f3fb-11e4-96ec-9d5e81b8eaa8.png)

Multi measure mode:

- title: DSD label (will be changed to dataset title when datasets supported)
- subtitle: null
- yAxis: null
- xAxis: last multi-valued dimension label
- legend: list of labels of single-valued dimensions and label of that single value

Notes: If no label is present, URI is used. We don't use subtitle right now and we could.

![screenshot 2015-05-06 13 32 03](https://cloud.githubusercontent.com/assets/174768/7492775/bfb1c8ae-f3fb-11e4-9066-5e41485c278b.png)
