### ISSUE TITLE
Side menu of data cube visualizer needs scrollbar when embedded to a smaller space

### ISSUE THREAD

**Issue by martinnec** [payola/LDVMi#48]
When the data cube visualizer is embedded to a space with a height smaller than the height of the side menu for setting dimension values and choosing measures, it is not visible whole and it is not possible to scroll it. Maybe adding a scrollbar to the side menu could help?

See

http://internal.opendata.cz/dataset/mfcrapp-rozpocty-a-populace-okresy-predskolni-a-zakladni-vzdelavani/resource/1c6aa5f8-99ac-49d7-8af8-2e82820c2cbe

**Comment by jirihelmich** [comment]
Btw. should I swap the function of left and right panels so that I would put the options into the pinnable panel on the left?

Or should I make the right one pinnable?
